on: [push]
name: Build

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            target_name: amd64
          - target: aarch64-unknown-linux-gnu
            target_name: arm64
          - target: arm-unknown-linux-gnueabi
            target_name: arm
          - target: arm-unknown-linux-gnueabihf
            target_name: armhf

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install pkg-config \
            librust-openssl-dev libssl-dev \
            openssl librust-openssl-sys-dev
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - name: Clean
        uses: actions-rs/cargo@v1
        with:
          command: clean
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --target ${{ matrix.target }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: gdlib-loader-${{ matrix.target_name }}.node
          tag_name: ${{ github.sha }}
